version: "2.1"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: ${HOSTNAME}
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RMUSER}
      - RABBITMQ_DEFAULT_PASS=${RMPASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit ${DISK_FREE_LIMIT}
    volumes:
      - ${DATA_PATH}/rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672


